---
- name: Get docker ps output
  hosts: all
  become: yes
  tasks:
    - name: Run docker ps command
      command: docker ps
      register: docker_ps_output

    - name: Show docker ps output
      debug:
        var: docker_ps_output.stdout